#! /usr/bin/env bash

ask__ () {
  local prompt=$@
  echo Asking $prompt
  echo Answer:
  python openai.chat.py "$prompt"
}

console__ () {
  while true; do
    read -rp "> " input
    if [[ -z "$input" ]]; then
      break
    fi
    ask__ $input
  done
}

. undies
