#! /usr/bin/env bash

__main__ () {
  init__ && console__
}

init__ () {
  if [ ! -e key/openai.api_key ]; then
    echo No key found.
    echo @see key/README.md
    return 1
  fi
}

console__help='@does open a console for prompting'
console__() {
  # Initialize command history file
  local HISTFILE="prompt_history.txt"
  touch $HISTFILE
  while true; do
      # Read the user input with command history functionality provided by rlwrap
      cmd=$(rlwrap -H $HISTFILE -S "> " -o cat)
      if [ -z "$cmd" ]; then
          # Exit if the command is empty
          break
      fi
      # Run the command and store the output
      python3 chipline_openai.py chat "$cmd"
  done
}

__main__ $@
