#! /usr/bin/env bash

OPENAI_API_KEY_PATH=${OPENAI_API_KEY_PATH:-'key/openai.api_key'}

__main__ () {
  init__ && console__
}

init__ () {
  if [ "${OPENAI_API_KEY}" ]; then
    return
  fi
  if [ ! -e "${OPENAI_API_KEY_PATH}" ]; then
    echo No key set or key path found.
    echo Given api key path: $OPENAI_API_KEY_PATH
    echo @see key/README.md
    return 1
  fi
}

console__help='@does open a console for prompting'
console__() {
  # Initialize command history file
  local HISTFILE="prompt_history.txt"
  touch $HISTFILE
  while true; do
      # Read the user input with command history functionality provided by rlwrap
      cmd=$(rlwrap -H $HISTFILE -S "> " -o cat)
      if [ -z "$cmd" ]; then
          # Exit if the command is empty
          break
      fi
      # Run the command and store the output
      python3 chipline_openai.py chat "$cmd"
  done
}

__main__ $@
